import { buildPageMetadata } from "@/lib/metadata";

// Option One Can Be Dynamic From Database

// export async function generateMetadata(): Promise<Metadata> {
//   const locale = await getLocale();

//   return locale === "ar"
//     ? {
//         title: "انشاء تطبيق نكست",
//         description: "تم انشاءه بواسطة انشاء تطبيق نكست",
//       }
//     : {
//         title: "Create Next App",
//         description: "Generated by create next app",
//       };
// }

// Option Two Can Be Extracted From Translation Files

export async function generateMetadata({
  params,
}: {
  params: { locale: string };
}) {
  return buildPageMetadata({ locale: params.locale, page: "home" });
}

export default function Home() {
  return (
    <>
      <main className="container mx-auto p-4"></main>
    </>
  );
}
